<!DOCTYPE html>
<html>
<head>
    <title>Balance Sheet</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .meta {
            font-size: 12px;
            color: #666;
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            background: #f4f4f4;
            padding: 8px;
        }
        .item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #eee;
        }
        .total {
            font-weight: bold;
            margin-top: 10px;
            padding: 10px 0;
            border-top: 2px solid #000;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company">{{ $company }}</div>
        <div class="meta">
            Balance Sheet<br>
            Period: {{ \Carbon\Carbon::parse($reportData['period']['start'])->format('d M Y') }} - 
                    {{ \Carbon\Carbon::parse($reportData['period']['end'])->format('d M Y') }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Assets</div>
        @foreach($reportData['assets'] as $asset)
            <div class="item">
                <span>{{ $asset['name'] }}</span>
                <span>Rp {{ number_format($asset['balance'], 2) }}</span>
            </div>
        @endforeach
        <div class="total">
            <div class="item">
                <span>Total Assets</span>
                <span>Rp {{ number_format($reportData['total_assets'], 2) }}</span>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Liabilities</div>
        @foreach($reportData['liabilities'] as $liability)
            <div class="item">
                <span>{{ $liability['name'] }}</span>
                <span>Rp {{ number_format($liability['balance'], 2) }}</span>
            </div>
        @endforeach
        <div class="total">
            <div class="item">
                <span>Total Liabilities</span>
                <span>Rp {{ number_format($reportData['total_liabilities'], 2) }}</span>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Equity</div>
        @foreach($reportData['equity'] as $equity)
            <div class="item">
                <span>{{ $equity['name'] }}</span>
                <span>Rp {{ number_format($equity['balance'], 2) }}</span>
            </div>
        @endforeach
        <div class="total">
            <div class="item">
                <span>Total Equity</span>
                <span>Rp {{ number_format($reportData['total_equity'], 2) }}</span>
            </div>
        </div>
    </div>

    <div class="footer">
        Generated by: {{ $generated_by }} | Date: {{ $generated_at }}
    </div>
</body>
</html>
