<!DOCTYPE html>
<html>
<head>
    <title>Budget Utilization Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .meta-info {
            margin-bottom: 30px;
            font-size: 0.9em;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        .summary-box {
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 0.9em;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.8em;
            color: #666;
        }
        .progress-bar {
            width: 100%;
            background-color: #f0f0f0;
            padding: 3px;
            border-radius: 3px;
            box-sizing: border-box;
        }
        .progress-bar-fill {
            background-color: #4299e1;
            height: 20px;
            border-radius: 3px;
            transition: width 500ms ease-in-out;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Budget Utilization Report</h1>
        <div class="company-info">
            <h2>{{ $company }}</h2>
        </div>
    </div>

    <div class="meta-info">
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>

    <div class="summary-grid">
        <div class="summary-box">
            <h3>Total Projects</h3>
            <p>{{ number_format($reportData['summary']['total_projects']) }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Budget</h3>
            <p>Rp {{ number_format($reportData['summary']['total_budget'], 2) }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Spent</h3>
            <p>Rp {{ number_format($reportData['summary']['total_spent'], 2) }}</p>
        </div>
        <div class="summary-box">
            <h3>Average Utilization</h3>
            <p>{{ number_format($reportData['summary']['average_utilization'], 1) }}%</p>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Client</th>
                <th>Manager</th>
                <th>Budget</th>
                <th>Actual Cost</th>
                <th>Utilization</th>
                <th>Progress</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['projects'] as $project)
                <tr>
                    <td>{{ $project->project_name }}</td>
                    <td>{{ $project->client_name }}</td>
                    <td>{{ $project->manager_first_name }} {{ $project->manager_last_name }}</td>
                    <td>Rp {{ number_format($project->planned_budget, 2) }}</td>
                    <td>Rp {{ number_format($project->actual_cost, 2) }}</td>
                    <td>{{ number_format($project->budget_utilization_percentage, 1) }}%</td>
                    <td>
                        <div class="progress-bar">
                            <div class="progress-bar-fill" style="width: {{ $project->completion_percentage }}%"></div>
                        </div>
                        {{ number_format($project->completion_percentage, 1) }}%
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated document. No signature is required.</p>
        <p>© {{ date('Y') }} {{ $company }}. All rights reserved.</p>
    </div>
</body>
</html>
