<!DOCTYPE html>
<html>
<head>
    <title>Cash Flow Statement</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0; 
        }
        .table th, .table td { 
            border: 1px solid #ddd; 
            padding: 12px; 
            text-align: left; 
        }
        .table th { 
            background-color: #f4f4f4; 
        }
        .total-row {
            font-weight: bold;
            background-color: #f8f8f8;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .positive { color: #0d9488; }
        .negative { color: #dc2626; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Cash Flow Statement</h1>
        <h3>{{ $company }}</h3>
        <p>Period: {{ \Carbon\Carbon::parse($reportData['period']['start'])->format('d M Y') }} - 
           {{ \Carbon\Carbon::parse($reportData['period']['end'])->format('d M Y') }}</p>
    </div>

    <table class="table">
        <tr>
            <th colspan="2">Operating Activities</th>
        </tr>
        <tr>
            <td>Net Operating Cash Flow</td>
            <td class="{{ $reportData['operating_cash_flow'] >= 0 ? 'positive' : 'negative' }}">
                Rp {{ number_format($reportData['operating_cash_flow'], 2) }}
            </td>
        </tr>

        <tr>
            <th colspan="2">Investing Activities</th>
        </tr>
        <tr>
            <td>Net Investing Cash Flow</td>
            <td class="{{ $reportData['investing_cash_flow'] >= 0 ? 'positive' : 'negative' }}">
                Rp {{ number_format($reportData['investing_cash_flow'], 2) }}
            </td>
        </tr>

        <tr>
            <th colspan="2">Financing Activities</th>
        </tr>
        <tr>
            <td>Net Financing Cash Flow</td>
            <td class="{{ $reportData['financing_cash_flow'] >= 0 ? 'positive' : 'negative' }}">
                Rp {{ number_format($reportData['financing_cash_flow'], 2) }}
            </td>
        </tr>

        <tr class="total-row">
            <td>Net Cash Flow</td>
            <td class="{{ $reportData['net_cash_flow'] >= 0 ? 'positive' : 'negative' }}">
                Rp {{ number_format($reportData['net_cash_flow'], 2) }}
            </td>
        </tr>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>
</body>
</html>
