<!DOCTYPE html>
<html>
<head>
    <title>Customer Retention Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .company-info {
            margin-bottom: 20px;
            font-size: 14px;
        }
        .metrics-container {
            display: flex;
            justify-content: space-between;
            margin: 20px 0;
            padding: 15px;
            background: #f8f8f8;
        }
        .metric-box {
            text-align: center;
            padding: 10px;
            background: white;
            border-radius: 5px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            width: 30%;
        }
        .metric-title {
            font-size: 12px;
            color: #666;
            margin-bottom: 5px;
        }
        .metric-value {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }
        .table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Retention Report</h1>
        <div class="company-info">
            <p>{{ $company }}</p>
            <p>Period: {{ \Carbon\Carbon::parse($start_date)->format('d M Y') }} - {{ \Carbon\Carbon::parse($end_date)->format('d M Y') }}</p>
        </div>
    </div>

    <div class="metrics-container">
        <div class="metric-box">
            <div class="metric-title">Previous Period Customers</div>
            <div class="metric-value">{{ number_format($reportData['total_previous_customers']) }}</div>
        </div>
        <div class="metric-box">
            <div class="metric-title">Returning Customers</div>
            <div class="metric-value">{{ number_format($reportData['returning_customers']) }}</div>
        </div>
        <div class="metric-box">
            <div class="metric-title">Retention Rate</div>
            <div class="metric-value">{{ number_format($reportData['retention_rate'], 1) }}%</div>
        </div>
    </div>

    <h3>Returning Customer Details</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Email</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['customer_details'] as $customer)
                <tr>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->email }}</td>
                    <td>Returning Customer</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }} | Date: {{ $generated_at }}</p>
    </div>
</body>
</html>
