<!DOCTYPE html>
<html>
<head>
    <title>Employee Performance Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .meta-info {
            margin-bottom: 30px;
            font-size: 0.9em;
            color: #666;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }
        .summary-box {
            border: 1px solid #ddd;
            padding: 15px;
            border-radius: 5px;
            background: #f8f8f8;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .performance-high {
            color: #059669;
            font-weight: bold;
        }
        .performance-medium {
            color: #b45309;
            font-weight: bold;
        }
        .performance-low {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.8em;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Employee Performance Report</h1>
        <div class="company-info">
            <h2>{{ $company }}</h2>
        </div>
        <div class="meta-info">
            <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
            <p>Generated: {{ $generated_at }}</p>
            <p>Generated by: {{ $generated_by }}</p>
        </div>
    </div>

    <div class="summary-grid">
        <div class="summary-box">
            <h3>Total Employees</h3>
            <p>{{ number_format($reportData['employees']->count()) }}</p>
        </div>
        <div class="summary-box">
            <h3>Average Attendance Rate</h3>
            <p>{{ number_format($reportData['employees']->avg('attendance_rate'), 1) }}%</p>
        </div>
        <div class="summary-box">
            <h3>Overall Performance</h3>
            <p>{{ number_format($reportData['employees']->avg(function($employee) {
                return $employee->attendance_rate - $employee->late_count;
            }), 1) }}%</p>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Employee Name</th>
                <th>Employee Code</th>
                <th>Attendance Rate</th>
                <th>Late Count</th>
                <th>Performance Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['employees'] as $employee)
                <tr>
                    <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                    <td>{{ $employee->employee_code }}</td>
                    <td>{{ number_format($employee->attendance_rate, 1) }}%</td>
                    <td>{{ $employee->late_count }}</td>
                    <td class="{{ 
                        (($employee->attendance_rate - $employee->late_count) >= 90) ? 'performance-high' : 
                        (($employee->attendance_rate - $employee->late_count) >= 75 ? 'performance-medium' : 
                        'performance-low')
                    }}">
                        {{ number_format($employee->attendance_rate - $employee->late_count, 1) }}%
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated document. No signature is required.</p>
        <p>© {{ date('Y') }} {{ $company }}. All rights reserved.</p>
    </div>
</body>
</html>
