<!DOCTYPE html>
<html>
<head>
    <title>Employee Turnover Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header { 
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        .summary-box {
            border: 1px solid #ddd;
            padding: 15px;
            border-radius: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .section-title {
            margin: 20px 0;
            color: #333;
            border-bottom: 2px solid #666;
            padding-bottom: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Employee Turnover Report</h1>
        <p>{{ $company }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
    </div>

    <div class="summary-grid">
        <div class="summary-box">
            <h3>Total New Hires</h3>
            <p>{{ $reportData['summary']['total_new_hires'] }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Exits</h3>
            <p>{{ $reportData['summary']['total_exits'] }}</p>
        </div>
        <div class="summary-box">
            <h3>Net Change</h3>
            <p>{{ $reportData['summary']['net_change'] }}</p>
        </div>
        <div class="summary-box">
            <h3>Turnover Rate</h3>
            <p>{{ number_format($reportData['summary']['turnover_rate'], 1) }}%</p>
        </div>
    </div>

    <h2 class="section-title">New Hires</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Employee Name</th>
                <th>Employee Code</th>
                <th>Join Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['new_hires'] as $employee)
                <tr>
                    <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                    <td>{{ $employee->employee_code }}</td>
                    <td>{{ \Carbon\Carbon::parse($employee->date_of_joining)->format('d M Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Exits</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Employee Name</th>
                <th>Employee Code</th>
                <th>Exit Date</th>
                <th>Exit Type</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['exits'] as $employee)
                <tr>
                    <td>{{ $employee->first_name }} {{ $employee->last_name }}</td>
                    <td>{{ $employee->employee_code }}</td>
                    <td>{{ \Carbon\Carbon::parse($employee->exit_date)->format('d M Y') }}</td>
                    <td>{{ ucfirst($employee->exit_type) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }} | Date: {{ $generated_at }}</p>
    </div>
</body>
</html>
