<!DOCTYPE html>
<html>
<head>
    <title>Lead Conversion Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 20px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .metrics-container {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
        }
        .metric-box {
            background: #f8f8f8;
            padding: 15px;
            border-radius: 5px;
            width: 30%;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .section-title {
            margin-top: 30px;
            color: #333;
            border-bottom: 2px solid #eee;
            padding-bottom: 5px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Lead Conversion Report</h1>
        <p>{{ $company }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
    </div>

    <div class="metrics-container">
        <div class="metric-box">
            <h3>Total Leads</h3>
            <p>{{ number_format($reportData['total_leads']) }}</p>
        </div>
        <div class="metric-box">
            <h3>Converted Leads</h3>
            <p>{{ number_format($reportData['converted_leads']) }}</p>
        </div>
        <div class="metric-box">
            <h3>Conversion Rate</h3>
            <p>{{ number_format($reportData['conversion_rate'], 1) }}%</p>
        </div>
    </div>

    <h2 class="section-title">Conversion by Stage</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Stage</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['stage_conversion'] as $stage => $count)
                <tr>
                    <td>{{ $stage }}</td>
                    <td>{{ number_format($count) }}</td>
                    <td>{{ number_format(($count / $reportData['total_leads']) * 100, 1) }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2 class="section-title">Recent Conversions</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Customer</th>
                <th>Email</th>
                <th>Stage</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['recent_conversions'] as $conversion)
                <tr>
                    <td>{{ $conversion->name }}</td>
                    <td>{{ $conversion->email }}</td>
                    <td>{{ json_decode($conversion->interaction_type)->stage ?? 'Unknown' }}</td>
                    <td>{{ \Carbon\Carbon::parse($conversion->created_at)->format('d M Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }} | Date: {{ $generated_at }}</p>
    </div>
</body>
</html>
