<!DOCTYPE html>
<html>
<head>
    <title>Payroll Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .summary-section {
            margin: 20px 0;
            padding: 15px;
            background: #f8f8f8;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 20px;
        }
        .summary-box {
            padding: 10px;
            background: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
        }
        .status-paid {
            color: #0d9488;
            font-weight: bold;
        }
        .status-pending {
            color: #d97706;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payroll Report</h1>
        <p>{{ $company }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
    </div>

    <div class="summary-section">
        <h3>Summary</h3>
        <div class="summary-grid">
            <div class="summary-box">
                <strong>Total Payroll</strong>
                <div>Rp {{ number_format($reportData['summary']['total_payroll'], 2) }}</div>
            </div>
            <div class="summary-box">
                <strong>Total Employees</strong>
                <div>{{ number_format($reportData['summary']['total_employees']) }}</div>
            </div>
            <div class="summary-box">
                <strong>Average Salary</strong>
                <div>Rp {{ number_format($reportData['summary']['average_salary'], 2) }}</div>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Employee</th>
                <th>Employee Code</th>
                <th>Basic Salary</th>
                <th>Allowances</th>
                <th>Deductions</th>
                <th>Net Salary</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['payroll_details'] as $payroll)
                <tr>
                    <td>{{ $payroll->first_name }} {{ $payroll->last_name }}</td>
                    <td>{{ $payroll->employee_code }}</td>
                    <td>Rp {{ number_format($payroll->basic_salary, 2) }}</td>
                    <td>Rp {{ number_format($payroll->allowances, 2) }}</td>
                    <td>Rp {{ number_format($payroll->deductions, 2) }}</td>
                    <td>Rp {{ number_format($payroll->net_salary, 2) }}</td>
                    <td class="status-{{ $payroll->payment_status }}">
                        {{ ucfirst($payroll->payment_status) }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>
</body>
</html>
