<!DOCTYPE html>
<html>
<head>
    <title>Product Performance Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0;
        }
        .table th, .table td { 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
        }
        .table th { 
            background-color: #f4f4f4; 
        }
        .summary-box { 
            margin: 20px 0; 
            padding: 15px; 
            background: #f8f8f8;
            border-radius: 5px;
        }
        .section-title {
            background: #2c5282;
            color: white;
            padding: 10px;
            margin: 20px 0 10px 0;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Product Performance Report</h1>
        <div class="company-info">
            <h3>{{ $company }}</h3>
            <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
        </div>
    </div>

    <div class="summary-box">
        <h3>Summary</h3>
        <table class="table">
            <tr>
                <th>Total Revenue</th>
                <td>Rp {{ number_format($reportData['total_revenue'], 2) }}</td>
            </tr>
            <tr>
                <th>Total Transactions</th>
                <td>{{ number_format($reportData['total_transactions']) }}</td>
            </tr>
        </table>
    </div>

    <div class="section-title">Top 5 Performing Products</div>
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity Sold</th>
                <th>Revenue</th>
                <th>Transaction Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['top_products'] as $product)
                <tr>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ number_format($product->total_quantity) }}</td>
                    <td>Rp {{ number_format($product->total_revenue, 2) }}</td>
                    <td>{{ number_format($product->transaction_count) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Bottom 5 Performing Products</div>
    <table class="table">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity Sold</th>
                <th>Revenue</th>
                <th>Transaction Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['bottom_products'] as $product)
                <tr>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ number_format($product->total_quantity) }}</td>
                    <td>Rp {{ number_format($product->total_revenue, 2) }}</td>
                    <td>{{ number_format($product->transaction_count) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $generated_by }} | Date: {{ $generated_at }}</p>
    </div>
</body>
</html>
