<!DOCTYPE html>
<html>
<head>
    <title>Resource Allocation Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        .meta-info {
            margin-bottom: 20px;
            font-size: 0.9em;
            color: #666;
        }
        .summary-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-bottom: 30px;
        }
        .summary-box {
            flex: 1;
            min-width: 200px;
            padding: 15px;
            background: #f8f8f8;
            border-radius: 5px;
        }
        .table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px; 
        }
        .table th, .table td { 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
        }
        .table th { 
            background-color: #f4f4f4; 
        }
        .resource-type {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 0.8em;
        }
        .type-human { background: #e3f2fd; color: #1565c0; }
        .type-material { background: #e8f5e9; color: #2e7d32; }
        .type-financial { background: #fff3e0; color: #f57c00; }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 0.8em;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Resource Allocation Report</h1>
    </div>

    <div class="company-info">
        <h2>{{ $company }}</h2>
    </div>

    <div class="meta-info">
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>

    <div class="summary-grid">
        <div class="summary-box">
            <h3>Total Resources</h3>
            <p>{{ number_format($reportData['summary']['total_resources']) }}</p>
        </div>
        <div class="summary-box">
            <h3>Total Cost</h3>
            <p>Rp {{ number_format($reportData['summary']['total_cost'], 2) }}</p>
        </div>
        <div class="summary-box">
            <h3>Human Resources</h3>
            <p>{{ number_format($reportData['summary']['human_resources']) }}</p>
        </div>
        <div class="summary-box">
            <h3>Material Resources</h3>
            <p>{{ number_format($reportData['summary']['material_resources']) }}</p>
        </div>
        <div class="summary-box">
            <h3>Financial Resources</h3>
            <p>{{ number_format($reportData['summary']['financial_resources']) }}</p>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Project</th>
                <th>Resource Name</th>
                <th>Type</th>
                <th>Cost</th>
                <th>Allocation Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['resources'] as $resource)
                <tr>
                    <td>{{ $resource->project_name }}</td>
                    <td>
                        @if($resource->resource_type === 'human')
                            {{ $resource->first_name }} {{ $resource->last_name }}
                        @else
                            {{ $resource->resource_name }}
                        @endif
                    </td>
                    <td>
                        <span class="resource-type type-{{ $resource->resource_type }}">
                            {{ ucfirst($resource->resource_type) }}
                        </span>
                    </td>
                    <td>Rp {{ number_format($resource->resource_cost, 2) }}</td>
                    <td>{{ number_format($resource->allocation_count) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>© {{ date('Y') }} {{ $company }}. All rights reserved.</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html>
