<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Summary Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .company-info {
            margin-bottom: 20px;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }
        .metric-card {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
        }
        .metric-title {
            font-size: 14px;
            color: #666;
            margin-bottom: 5px;
        }
        .metric-value {
            font-size: 24px;
            font-weight: bold;
            color: #2d3748;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Summary Report</h1>
        <p>{{ $company }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($reportData['period']['start'])->format('d M Y') }} - 
           {{ \Carbon\Carbon::parse($reportData['period']['end'])->format('d M Y') }}</p>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-title">Total Transactions</div>
            <div class="metric-value">{{ number_format($reportData['total_transactions']) }}</div>
        </div>
        <div class="metric-card">
            <div class="metric-title">Total Sales</div>
            <div class="metric-value">Rp {{ number_format($reportData['total_sales'], 2) }}</div>
        </div>
        <div class="metric-card">
            <div class="metric-title">Average Sale Value</div>
            <div class="metric-value">Rp {{ number_format($reportData['average_sale'], 2) }}</div>
        </div>
        <div class="metric-card">
            <div class="metric-title">Unique Customers</div>
            <div class="metric-value">{{ number_format($reportData['unique_customers']) }}</div>
        </div>
    </div>

    <div class="footer">
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>
</body>
</html>
