<!DOCTYPE html>
<html>
<head>
    <title>Sales Forecast Report</title> 
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
        }
        .company-info {
            margin-bottom: 20px;
        }
        .table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px; 
        }
        .table th, .table td { 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
        }
        .table th { 
            background-color: #f4f4f4; 
        }
        .metrics-box { 
            margin: 20px 0; 
            padding: 15px; 
            background: #f8f8f8; 
        }
        .section-title {
            background: #4a5568;
            color: white;
            padding: 10px;
            margin-top: 20px;
        }
        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Forecast Report</h1>
        <div class="company-info">
            <h3>{{ $company }}</h3>
            <p>Generated on: {{ $generated_at }}</p>
            <p>Generated by: {{ $generated_by }}</p>
        </div>
    </div>

    <div class="metrics-box">
        <h3>Growth Metrics</h3>
        <p>Average Monthly Growth Rate: {{ number_format($reportData['average_growth_rate'], 2) }}%</p>
    </div>

    <div class="section-title">Historical Sales Data</div>
    <table class="table">
        <thead>
            <tr>
                <th>Month</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['historical_data'] as $data)
                <tr>
                    <td>{{ $data['month'] }}</td>
                    <td>Rp {{ number_format($data['amount'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Sales Forecast (Next 6 Months)</div>
    <table class="table">
        <thead>
            <tr>
                <th>Month</th>
                <th>Forecast Amount</th>
                <th>Growth Rate</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['forecast_data'] as $forecast)
                <tr>
                    <td>{{ $forecast['month'] }}</td>
                    <td>Rp {{ number_format($forecast['amount'], 2) }}</td>
                    <td>{{ number_format($forecast['growth_rate'], 2) }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Report Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} - {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
        <p>This forecast is based on historical sales data and trends. Actual results may vary.</p>
    </div>
</body>
</html>
