<!DOCTYPE html>
<html>
<head>
    <title>Stock Level Report</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
        }
        .company-info {
            margin-bottom: 20px;
        }
        .meta-info {
            margin-bottom: 30px;
            font-size: 12px;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-bottom: 30px;
        }
        .summary-box {
            padding: 15px;
            background: #f8f8f8;
            border-radius: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 12px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 11px;
        }
        .status-in-stock {
            background-color: #dcfce7;
            color: #166534;
        }
        .status-out-of-stock {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .status-low-stock {
            background-color: #fef3c7;
            color: #92400e;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stock Level Report</h1>
        <div class="company-info">{{ $company }}</div>
    </div>

    <div class="meta-info">
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>

    <div class="summary-grid">
        <div class="summary-box">
            <h3>Inventory Summary</h3>
            <p>Total Items: {{ number_format($reportData['summary']['total_items']) }}</p>
            <p>Out of Stock: {{ number_format($reportData['summary']['out_of_stock']) }}</p>
            <p>Low Stock: {{ number_format($reportData['summary']['low_stock']) }}</p>
            <p>Total Value: Rp {{ number_format($reportData['summary']['total_value'], 2) }}</p>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Item Name</th>
                <th>SKU</th>
                <th>Quantity</th>
                <th>Location</th>
                <th>Status</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['inventories'] as $item)
                <tr>
                    <td>{{ $item->item_name }}</td>
                    <td>{{ $item->sku }}</td>
                    <td>{{ number_format($item->quantity) }}</td>
                    <td>{{ $item->location }}</td>
                    <td>
                        <span class="status-badge status-{{ $item->status }}">
                            {{ ucfirst(str_replace('_', ' ', $item->status)) }}
                        </span>
                    </td>
                    <td>Rp {{ number_format($item->quantity * $item->purchase_price, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated document. No signature is required.</p>
        <p>Page 1 of 1</p>
    </div>
</body>
</html>
