<!DOCTYPE html>
<html>

<head>
    <title>Supplier Transaction Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .company {
            font-size: 20px;
            font-weight: bold;
        }

        .period {
            color: #666;
            margin: 10px 0;
        }

        .summary {
            margin: 20px 0;
            padding: 15px;
            background: #f8f8f8;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .table th {
            background-color: #f4f4f4;
        }

        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="company">{{ $company }}</div>
        <h1>Supplier Transaction Report</h1>
        <div class="period">
            Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} -
            {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}
        </div>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <table class="table">
            <tr>
                <th>Total Transactions</th>
                <td>{{ number_format($reportData['summary']['total_transactions']) }}</td>
                <th>Total Amount</th>
                <td>Rp {{ number_format($reportData['summary']['total_amount'], 2) }}</td>
            </tr>
            <tr>
                <th>Total Items</th>
                <td>{{ number_format($reportData['summary']['total_items']) }}</td>
                <th>Total Quantity</th>
                <td>{{ number_format($reportData['summary']['total_quantity']) }}</td>
            </tr>
        </table>
    </div>

    <h3>Transaction Details</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Supplier</th>
                <th>Code</th>
                <th>Date</th>
                <th>Status</th>
                <th>Items</th>
                <th>Quantity</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['transactions'] as $transaction)
                <tr>
                    <td>{{ $transaction->supplier_name }}</td>
                    <td>{{ $transaction->supplier_code }}</td>
                    <td>{{ \Carbon\Carbon::parse($transaction->transaction_date)->format('d M Y') }}</td>
                    <td>{{ ucfirst($transaction->status) }}</td>
                    <td>{{ number_format($transaction->total_items) }}</td>
                    <td>{{ number_format($transaction->total_quantity) }}</td>
                    <td>Rp {{ number_format($transaction->total_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by: {{ $generated_by }} | Date: {{ $generated_at }}
    </div>
</body>

</html>
