<!DOCTYPE html>
<html>

<head>
    <title>Supplier Performance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        .table th {
            background-color: #f4f4f4;
        }

        .summary {
            margin: 20px 0;
            padding: 15px;
            background: #f8f8f8;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Supplier Performance Report</h1>
        <p>{{ $company }}</p>
        <p>Period: {{ \Carbon\Carbon::parse($period['start'])->format('d M Y') }} -
            {{ \Carbon\Carbon::parse($period['end'])->format('d M Y') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p>Total Suppliers: {{ number_format($reportData['summary']['total_suppliers']) }}</p>
        <p>Average Quality Score: {{ number_format($reportData['summary']['average_quality_score'], 2) }}%</p>
        <p>Total Transactions: {{ number_format($reportData['summary']['total_transactions']) }}</p>
        <p>Total Purchase Value: Rp {{ number_format($reportData['summary']['total_purchase_value'], 2) }}</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Supplier Code</th>
                <th>Supplier Name</th>
                <th>Total Transactions</th>
                <th>On-Time Deliveries</th>
                <th>Quality Score</th>
                <th>Total Purchase Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reportData['suppliers'] as $supplier)
                <tr>
                    <td>{{ $supplier->supplier_code }}</td>
                    <td>{{ $supplier->supplier_name }}</td>
                    <td>{{ number_format($supplier->total_transactions) }}</td>
                    <td>{{ number_format($supplier->on_time_deliveries) }}</td>
                    <td>{{ number_format($supplier->quality_score, 2) }}%</td>
                    <td>Rp {{ number_format($supplier->total_purchase_value, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 20px;">
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>
</body>

</html>
